### ISSUE TITLE
Issue connecting to google.com or discord.com

### ISSUE THREAD

**Issue by lulf** [drogue-iot/embedded-tls#75]
When connecting to these endpoints, the handshake ends with an InvalidSignature error, as something in the key schedule transcript is not verified.

One difference with these hosts compared to http.sandbox.drogue.cloud, is that they batch more records into a single one in the handshake. One possibility is that there is a flaw in the decrypt/decoding logic in embedded-tls for that. 

The next step is to reproduce the 'batching' of records in the test server to see if we can reproduce the issue in the client, and then debug further.

**Comment by newAM** [comment]
Fragmented records can also occur in a TLS compliant server, e.g. two headers each with half of one record.

If I recall correctly stock nginx servers will reproduce this behaviour (multiple records in a single header), but openssl's CLI will not (perhaps there is a setting for this?)

**Comment by lulf** [comment]
I've not been able to reproduce the batching with nginx, but I'm going to modify the rustls test server so it can reproduce this behavior.

**Comment by beeb** [comment]
I'll test the fix for my use case later! Thanks for looking into this.

**Comment by beeb** [comment]
Not sure how to test until reqwless is updated to use this version. I added a `[patch.crates-io]` section to my config file but it's ignored because the versions don't match (0.12 is required by reqwless and 0.13 is in this repo's main branch).

**Comment by bugadani** [comment]
You can fork embedded-tls, modify the version number and use this fork as the patch.

**Comment by bugadani** [comment]
Or, I guess you can do this locally without forking :) Download the source, modify the version and use the local version as a patch.

**Comment by bugadani** [comment]
Oh shoot, that's my fault

**Comment by bugadani** [comment]
Unfortunately, I can't reproduce this error, and I don't have any idea why. Still, https://github.com/drogue-iot/embedded-tls/pull/107 is supposed to fix it

**Comment by beeb** [comment]
It also doesn't show when I `cargo check` on the embedded-tls repo, but it does when it's used by reqwless in my project.

**Comment by bugadani** [comment]
That's inconvenient because pulling in reqwless for automated tests seems less than ideal :)

**Comment by beeb** [comment]
The error mentions `digest::InvalidLength` but the code actually seems to use `crypto_common::InvalidLength`. No idea if that's an issue of it digest simply re-exports those types.

**Comment by beeb** [comment]
Ok i checked with your PR branch and it seems to compile fine now!

**Comment by beeb** [comment]
Regarding the original issue: I confirm that I can now send requests to the discord API!
The request went through, but I got errors in the logs still:

```
16.126670 DEBUG Resolved discord.com to 162.159.136.232
└─ test_rp_rs::{impl#0}::get_host_by_name::{async_fn#0} @ src\main.rs:192
16.156411 DEBUG start_record(Handshake(false))
└─ embedded_tls::write_buffer::{impl#0}::start_record @ C:\Users\valentin\.cargo\git\checkouts\embedded-tls-7f5f3f5b62563efe\59aa9cb\src\fmt.rs:125
17.611035 DEBUG Not decrypting: Not encapsulated in app data
└─ embedded_tls::connection::decrypt_record @ C:\Users\valentin\.cargo\git\checkouts\embedded-tls-7f5f3f5b62563efe\59aa9cb\src\fmt.rs:125
└─ embedded_tls::write_buffer::{impl#0}::start_record @ C:\Users\valentin\.cargo\git\checkouts\embedded-tls-7f5f3f5b62563efe\59aa9cb\src\fmt.rs:125
17.702040 DEBUG start_record(ApplicationData)
└─ embedded_tls::write_buffer::{impl#0}::start_record @ C:\Users\valentin\.cargo\git\checkouts\embedded-tls-7f5f3f5b62563efe\59aa9cb\src\fmt.rs:125
18.271279 INFO  Unsupported extension type EarlyData
└─ embedded_tls::extensions::server::{impl#2}::parse_vector @ C:\Users\valentin\.cargo\git\checkouts\embedded-tls-7f5f3f5b62563efe\59aa9cb\src\fmt.rs:138
18.271483 ERROR HTTP POST Error: Network(Other)
└─ test_rp_rs::____embassy_main_task::{async_fn#0}::{closure#1} @ src\main.rs:164
```

**Comment by bugadani** [comment]
That is the same error I've seen trying to do a GET against http://google.com - I don't know if this is embedded-tls or reqwless related, though.

**Comment by beeb** [comment]
Alright, something to investigate. Anyway, I'm really happy that I can continue experimenting now! Thanks for the fix :)

**Comment by lulf** [comment]
In your log there is

```18.271279 INFO  Unsupported extension type EarlyData````

The handshake will fail if encountering unsupported extensions.

**Comment by bugadani** [comment]
So, that is #11 I believe.

**Comment by bjoernQ** [comment]
Good to see this making progress.

Is it now expected to be able to connect to e.g. `google.com:443`?

At least when changing the blocking example to something like this
```rust
fn main() {
    env_logger::init();
    let stream = TcpStream::connect("google.com:443").expect("error connecting to server");

    log::info!("Connected");
    let mut read_record_buffer = [0; 16384];
    let mut write_record_buffer = [0; 16384];
    let config = TlsConfig::new().with_server_name("google.com");
    let mut tls: TlsConnection<FromStd<TcpStream>, Aes128GcmSha256> = TlsConnection::new(
        FromStd::new(stream),
        &mut read_record_buffer,
        &mut write_record_buffer,
    );
    let mut rng = OsRng;

    tls.open::<OsRng, NoVerify>(TlsContext::new(
        &config, &mut rng,
    ))
    .expect("error establishing TLS connection");

    tls.write_all(b"GET / HTTP/1.0\r\n\r\n").expect("error writing data");
    tls.flush().expect("error flushing data");

    let mut rx_buf = [0; 4096];
    let sz = tls.read(&mut rx_buf).expect("error reading data");
    log::info!("Read {} bytes: {:?}", sz, &rx_buf[..sz]);
}
```

I get this
```text
[2023-05-09T07:28:48Z INFO  ping_std] Connected
[2023-05-09T07:28:48Z DEBUG embedded_tls::write_buffer] start_record(Handshake(false))
[2023-05-09T07:28:48Z TRACE embedded_tls::blocking] State ClientHello -> ServerHello
[2023-05-09T07:28:48Z TRACE embedded_tls::handshake] handshake = ServerHello
[2023-05-09T07:28:48Z DEBUG embedded_tls::extensions::messages] Read extension type KeyShare
[2023-05-09T07:28:48Z DEBUG embedded_tls::extensions::messages] Read extension type SupportedVersions
[2023-05-09T07:28:48Z TRACE embedded_tls::connection] ********* ServerHello
[2023-05-09T07:28:48Z TRACE embedded_tls::blocking] State ServerHello -> ServerVerify
[2023-05-09T07:28:48Z TRACE embedded_tls::connection] Not decrypting: content_type = ChangeCipherSpec
[2023-05-09T07:28:48Z TRACE embedded_tls::blocking] State ServerVerify -> ServerVerify
[2023-05-09T07:28:48Z TRACE embedded_tls::connection] Decrypting: content type = Handshake
[2023-05-09T07:28:48Z TRACE embedded_tls::handshake] handshake = EncryptedExtensions
[2023-05-09T07:28:48Z TRACE embedded_tls::handshake] handshake = Certificate
[2023-05-09T07:28:48Z DEBUG embedded_tls::connection] Certificate verified!
[2023-05-09T07:28:48Z TRACE embedded_tls::handshake] handshake = CertificateVerify
[2023-05-09T07:28:48Z DEBUG embedded_tls::connection] Signature verified!
[2023-05-09T07:28:48Z TRACE embedded_tls::handshake] handshake = Finished
[2023-05-09T07:28:48Z TRACE embedded_tls::blocking] State ServerVerify -> ClientFinished
[2023-05-09T07:28:48Z DEBUG embedded_tls::write_buffer] start_record(Handshake(true))
[2023-05-09T07:28:48Z TRACE embedded_tls::connection] output size 53
[2023-05-09T07:28:48Z TRACE embedded_tls::blocking] State ClientFinished -> ApplicationData
[2023-05-09T07:28:48Z DEBUG embedded_tls::write_buffer] start_record(ApplicationData)
[2023-05-09T07:28:48Z TRACE embedded_tls::connection] output size 35
[2023-05-09T07:28:49Z TRACE embedded_tls::connection] Decrypting: content type = Handshake
[2023-05-09T07:28:49Z TRACE embedded_tls::handshake] handshake = NewSessionTicket
[2023-05-09T07:28:49Z DEBUG embedded_tls::extensions::messages] Read extension type EarlyData
[2023-05-09T07:28:49Z WARN  embedded_tls::extensions] Read unknown ExtensionType: 10794
[2023-05-09T07:28:49Z WARN  embedded_tls::extensions::messages] Failed to read extension type: InvalidData
[2023-05-09T07:28:49Z DEBUG embedded_tls::extensions::messages] Read extension type ServerName
thread 'main' panicked at 'error reading data: DecodeError', src\main.rs:33:36
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library\core\src\panicking.rs:65
   2: core::result::unwrap_failed
             at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab/library\core\src\result.rs:1791
   3: enum2$<core::result::Result<usize,enum2$<embedded_tls::TlsError> > >::expect<usize,enum2$<embedded_tls::TlsError> >
             at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab\library\core\src\result.rs:1070
   4: ping_std::main
             at .\src\main.rs:33
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/b7bc90fea3b441234a84b49fdafeb75815eebbab\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

But maybe I just did something wrong 😄 Just wanted to double check
